apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  namespace: slack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: slack }
  template:
    metadata:
      labels: { app: slack }
    spec:
      containers:
        - name: slack
          image: lscr.io/linuxserver/webtop:latest
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "2000m"
          volumeMounts:
            - name: slack-data
              mountPath: /config
      volumes:
        - name: slack-data
          persistentVolumeClaim:
            claimName: slack-data
