apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack
  namespace: slack
spec:
  ingressClassName: traefik
  rules:
    - host: slack.shrub.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slack
                port:
                  number: 3000
