apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack
  namespace: slack
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: slack
      port:
        number: 3000
  tls:
    - hosts:
        - slack
