apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: slack
  labels:
    app: slack
spec:
  type: ClusterIP
  selector:
    app: slack
  ports:
    - name: https
      port: 6901
      targetPort: 6901
      protocol: TCP
