apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: slack
  labels:
    app: slack
spec:
  type: ClusterIP
  selector:
    app: slack
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
