apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-ui-tls
  namespace: adguard
spec:
  secretName: adguard-ui-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - adguard.shrub.dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ui
  namespace: adguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: adguard.shrub.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-ui-external
                port:
                  number: 3000
  tls:
    - hosts: [adguard.shrub.dev]
      secretName: adguard-ui-tls
