apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puter
  namespace: puter
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: puter
      port:
        number: 4100
  tls:
    - hosts:
        - puter
