apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prison-mike
  namespace: prison-mike
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: prison-mike
      port:
        number: 18789
  tls:
    - hosts:
        - prison-mike
