apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtop
  namespace: webtop
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: webtop
      port:
        number: 3000
  tls:
    - hosts:
        - slack
