apiVersion: v1
kind: Service
metadata:
  name: webtop
  namespace: webtop
  labels:
    app: webtop
spec:
  type: ClusterIP
  selector:
    app: webtop
  ports:
    - name: http
      port: 3000
      targetPort: web
      protocol: TCP
