name: Validate Manifests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  kubeconform:
    name: Run kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:latest-alpine
        with:
          args: >
            -summary
            -ignore-missing-schemas
            -schema-location default
            -kubernetes-version 1.29.0
            src
