name: Scan for Deprecated APIs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pluto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run pluto
        uses: FairwindsOps/pluto/github-action@v5.22.7
        with:
          args: detect -d src --target-versions k8s=v1.29.0 --output wide
